[package]
name = "rust_tp"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam-channel = "0.5"
crossbeam-deque = "0.8"
core_affinity = "0.8"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "executor_benchmark"
harness = false